// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdhjlgttsqxebvcsrwbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkaGpsZ3R0c3F4ZWJ2Y3Nyd2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjA0NjAsImV4cCI6MjA2MDEzNjQ2MH0.1Kxtp1TflfUis-W-EUVmYIqo2JneIERLGI4WTF9sqLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);